[workspace]
authors = ["Ramiro Harguinteguy <ramirohar@gmail.com>"]
channels = ["conda-forge"]
name = "tracking"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
matplotlib = ">=3.10.3,<4"
numpy = ">=2.2.6,<3"
scikit-image = ">=0.25.2,<0.26"
ipykernel = ">=6.29.5,<7"
opencv = ">=4.11.0,<5"
pyserial = ">=3.5,<4"
smo = ">=2.0.2,<3"
scipy = ">=1.15.2,<2"
pandas = ">=2.2.3,<3"

